### ISSUE TITLE
Make Timeout a config option

### ISSUE THREAD

**Issue by nuclearspike** [5an1ty/kraken-api#2]
Kraken's API is quite slow many times and it's common that it takes longer than 5 sec to respond. By not getting the response, I don't know if the order went through or not without checking open orders. Please either set the default much higher or allow it to be passed in.

**Comment by 5an1ty** [comment]
Thanks for the feedback, I'll publish a fix when I got some time available or feel Free to submit a PR.

**Comment by 5an1ty** [comment]
Solved in v1.0.0
